# Generated by Django 4.1.6 on 2023-02-20 15:44

# from django.contrib.auth.models import Group, Permission
# from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from django.core.management.sql import emit_post_migrate_signal

GROUPS_PERMISSIONS = {
    'client': {},
    'service_company': {},
    'manager': {
        'machine': ['add', 'change', 'delete', 'view'],
        'maintenance': ['add', 'change', 'delete', 'view'],
        'complaint': ['add', 'change', 'delete', 'view'],
        'directory': ['add', 'change', 'delete', 'view'],
    }
}


def add_user_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    db_alias = schema_editor.connection.alias
    emit_post_migrate_signal(2, False, 'default')
    for group_name, models in GROUPS_PERMISSIONS.items():
        group, _ = Group.objects.using(db_alias).get_or_create(name=group_name)
        for model, perms in models.items():
            for perm in perms:
                p = Permission.objects.using(db_alias).select_related('content_type').get(
                    codename=f'{perm}_{model}',
                    content_type__app_label='moi_silant',
                    content_type__model=model
                )
                group.permissions.add(p)


class Migration(migrations.Migration):
    dependencies = [
        ('moi_silant', '0001_initial'),
        ('auth', '__latest__'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(add_user_groups),
    ]
